import { describe, it } from "mocha"
import { expect } from "chai"
import { toolParamNames, toolUseNames, type ToolUse } from "@core/assistant-message"
import { parseAssistantMessageV2 } from "@core/assistant-message/parse-assistant-message"
import { complianceCheckToolDefinition } from "@core/tools/complianceCheckTool"

/**
 * Wiring tests for compliance_check.
 *
 * The live system prompt is generated by the backend, but the *parsing* of the tool call
 * happens here. If the tool name or any parameter is missing from the registries below,
 * the model's call is silently dropped or its arguments are lost — a failure that would
 * look like "the AI ignored the tool" rather than a bug. These assertions cover the seam
 * between the backend-authored prompt and the extension-side parser.
 */

function firstToolUse(message: string): ToolUse {
	const parsed = parseAssistantMessageV2(message)
	const toolUse = parsed.find((block): block is ToolUse => block.type === "tool_use")
	expect(toolUse, "expected the message to parse into a tool use").to.not.equal(undefined)
	return toolUse!
}

describe("compliance_check wiring", () => {
	describe("registration", () => {
		it("is a known tool name", () => {
			expect(toolUseNames).to.include("compliance_check")
		})

		it("declares every parameter the backend prompt emits", () => {
			// These names must match complianceCheckToolDefinition in the backend's
			// system-prompt-generator.service.js. A parameter missing here parses as text
			// and is dropped from the tool call.
			for (const param of ["standard", "path", "mode", "tier", "rule_ids"]) {
				expect(toolParamNames, `missing tool param "${param}"`).to.include(param)
			}
		})

		it("keeps the local tool definition in step with the parameters", () => {
			const schemaParams = Object.keys(complianceCheckToolDefinition.inputSchema.properties ?? {})

			expect(complianceCheckToolDefinition.name).to.equal("compliance_check")
			for (const param of schemaParams) {
				expect(toolParamNames, `schema declares "${param}" but it is not a known tool param`).to.include(param)
			}
			expect(complianceCheckToolDefinition.inputSchema.required).to.deep.equal(["standard", "path"])
		})
	})

	describe("parsing the XML form the backend prompt teaches", () => {
		it("parses an analyze call", () => {
			const toolUse = firstToolUse(
				[
					"I will verify the file.",
					"<compliance_check>",
					"<standard>jf-avpp</standard>",
					"<path>src/flight_control.cpp</path>",
					"<mode>analyze</mode>",
					"</compliance_check>",
				].join("\n"),
			)

			expect(toolUse.name).to.equal("compliance_check")
			expect(toolUse.params.standard).to.equal("jf-avpp")
			expect(toolUse.params.path).to.equal("src/flight_control.cpp")
			expect(toolUse.params.mode).to.equal("analyze")
			expect(toolUse.partial).to.equal(false)
		})

		it("parses an autofix call with tier and rule ids", () => {
			const toolUse = firstToolUse(
				[
					"<compliance_check>",
					"<standard>jf-avpp</standard>",
					"<path>src/a.cpp</path>",
					"<mode>autofix</mode>",
					"<tier>review</tier>",
					"<rule_ids>150, 14</rule_ids>",
					"</compliance_check>",
				].join("\n"),
			)

			expect(toolUse.params.mode).to.equal("autofix")
			expect(toolUse.params.tier).to.equal("review")
			expect(toolUse.params.rule_ids).to.equal("150, 14")
		})

		it("omits absent optional parameters rather than inventing them", () => {
			const toolUse = firstToolUse(
				["<compliance_check>", "<standard>jf-avpp</standard>", "<path>a.cpp</path>", "</compliance_check>"].join("\n"),
			)

			expect(toolUse.params.mode).to.equal(undefined)
			expect(toolUse.params.tier).to.equal(undefined)
			expect(toolUse.params.rule_ids).to.equal(undefined)
		})

		it("marks an unterminated call as partial so it is not executed early", () => {
			const toolUse = firstToolUse(["<compliance_check>", "<standard>jf-avpp</standard>", "<path>a.cpp"].join("\n"))

			expect(toolUse.partial).to.equal(true)
		})

		it("preserves surrounding prose as text content", () => {
			const parsed = parseAssistantMessageV2(
				[
					"Checking now.",
					"<compliance_check>",
					"<standard>jf-avpp</standard>",
					"<path>a.cpp</path>",
					"</compliance_check>",
				].join("\n"),
			)

			const text = parsed.find((block) => block.type === "text")
			expect(text).to.not.equal(undefined)
			expect((text as { content: string }).content).to.contain("Checking now.")
		})

		it("carries a path containing spaces intact", () => {
			const toolUse = firstToolUse(
				[
					"<compliance_check>",
					"<standard>jf-avpp</standard>",
					"<path>src/flight control/main.cpp</path>",
					"</compliance_check>",
				].join("\n"),
			)

			expect(toolUse.params.path).to.equal("src/flight control/main.cpp")
		})

		it("accepts a standard id the extension has never heard of", () => {
			// The backend registry is the authority on which standards exist; the parser must
			// not constrain the value or a new rule pack would need an extension release.
			const toolUse = firstToolUse(
				["<compliance_check>", "<standard>do-178c</standard>", "<path>a.c</path>", "</compliance_check>"].join("\n"),
			)

			expect(toolUse.params.standard).to.equal("do-178c")
		})
	})
})
