import { ToolDefinition } from "@core/prompts/model_prompts/jsonToolToXml"

/**
 * Static analysis of source against a coding standard.
 *
 * `standard` is an open string rather than an enum on purpose: the backend registry is
 * the authority on which standards exist, so registering a new rule pack there makes it
 * usable here without shipping a new extension release.
 *
 * Note that the live system prompt is generated by the backend
 * (services/system-prompt-generator.service.js), which declares this tool only for the
 * JF-AV++ model. This definition exists for the JSON/antml prompt path and must be kept
 * in step with the backend's complianceCheckToolDefinition.
 */
export const complianceCheckToolDefinition: ToolDefinition = {
	name: "compliance_check",
	descriptionForAgent: `- Statically checks source files against a coding standard and reports every violation with its rule id, severity and line number
- Use after writing or modifying a file to verify the result actually complies, rather than assuming it does
- Set mode to "autofix" to get a patch that mechanically fixes what can be fixed safely
- Autofix never writes to disk: it returns the corrected content, which you must apply with write_to_file or replace_in_file so the user can review it
- A clean result covers only the rules that can be decided automatically; rules needing human judgement are reported separately and are NOT evidence of full conformance`,
	inputSchema: {
		type: "object",
		properties: {
			standard: {
				type: "string",
				description: "Id of the coding standard to check against, for example 'jf-avpp'",
			},
			path: {
				type: "string",
				description: "Path of the file to check, relative to the current working directory",
			},
			mode: {
				type: "string",
				description: "'analyze' (default) reports violations; 'autofix' returns corrected content and a diff",
			},
			tier: {
				type: "string",
				description:
					"Autofix only. 'safe' (default) applies deterministic, behaviour-preserving fixes; 'review' also applies fixes carrying semantic risk",
			},
			rule_ids: {
				type: "string",
				description: "Autofix only. Comma-separated rule ids to fix. Omit to fix everything the tier permits",
			},
		},
		required: ["standard", "path"],
	},
}
