import { getLanguageKey, LanguageDisplay, DEFAULT_LANGUAGE_SETTINGS } from "@shared/Languages"
import { formatResponse } from "./responses"

/**
 * System prompt generation for Aeriocode extension.
 * This handles user instructions collection and formatting locally in the extension,
 * while the backend handles the core system prompt generation based on model type.
 */

export interface SystemPromptContext {
	cwd: string
	osName: string
	shell: string
	homeDir: string
	browserWidth: number
	browserHeight: number
	mcpServers: Array<{
		name: string
		tools: any[]
		resources: any[]
		resourceTemplates: any[]
	}>
	browserSettings: any
	userInstructions?: string
}

/**
 * Collects and formats user instructions from various sources
 */
export function collectUserInstructions(
	globalAeriocodeRulesFileInstructions?: string,
	localAeriocodeRulesFileInstructions?: string,
	localCursorRulesFileInstructions?: string,
	localCursorRulesDirInstructions?: string,
	localWindsurfRulesFileInstructions?: string,
	aeriocodeIgnoreInstructions?: string,
	preferredLanguageInstructions?: string,
): string {
	const instructions: string[] = []

	if (preferredLanguageInstructions) {
		instructions.push(preferredLanguageInstructions)
	}

	if (globalAeriocodeRulesFileInstructions) {
		instructions.push(globalAeriocodeRulesFileInstructions)
	}

	if (localAeriocodeRulesFileInstructions) {
		instructions.push(localAeriocodeRulesFileInstructions)
	}

	if (localCursorRulesFileInstructions) {
		instructions.push(localCursorRulesFileInstructions)
	}

	if (localCursorRulesDirInstructions) {
		instructions.push(localCursorRulesDirInstructions)
	}

	if (localWindsurfRulesFileInstructions) {
		instructions.push(localWindsurfRulesFileInstructions)
	}

	if (aeriocodeIgnoreInstructions) {
		instructions.push(aeriocodeIgnoreInstructions)
	}

	if (instructions.length === 0) {
		return ""
	}

	return `\n====\n\nUSER'S CUSTOM INSTRUCTIONS\n\nThe following additional instructions are provided by the user, and should be followed to the best of your ability without interfering with the TOOL USE guidelines.\n\n${instructions.join("\n\n")}`
}

/**
 * Formats system prompt context for backend processing
 */
export function formatSystemPromptContext(
	contextInfo: any,
	userInstructions?: string
): SystemPromptContext {
	return {
		...contextInfo,
		userInstructions
	}
}

/**
 * Legacy function for backward compatibility
 */
export function addUserInstructions(
	globalAeriocodeRulesFileInstructions?: string,
	localAeriocodeRulesFileInstructions?: string,
	localCursorRulesFileInstructions?: string,
	localCursorRulesDirInstructions?: string,
	localWindsurfRulesFileInstructions?: string,
	aeriocodeIgnoreInstructions?: string,
	preferredLanguageInstructions?: string,
): string {
	return collectUserInstructions(
		globalAeriocodeRulesFileInstructions,
		localAeriocodeRulesFileInstructions,
		localCursorRulesFileInstructions,
		localCursorRulesDirInstructions,
		localWindsurfRulesFileInstructions,
		aeriocodeIgnoreInstructions,
		preferredLanguageInstructions,
	)
}

/**
 * Legacy async function for backward compatibility
 */
export const SYSTEM_PROMPT = async () => {
	// This function is no longer used - system prompts are generated by backend
	return ""
}
